# Connection settings
SERVER_PING_TIMEOUT = None

# Session constants
SESSION_CONNECTED    = "CONNECTED"
SESSION_DISCONNECTED = "DISCONNECTED"
SESSION_TERMINATED   = "TERMINATED"

# Algorithm constants
INITIAL_BACKOFF_TIME_IN_SECONDS = 0.25
MAX_BACKOFF_TIME_IN_SECONDS     = 8

# Message constants
MSG_CONNECTION   = "CONNECTION"
MSG_COMMAND      = "COMMAND"
MSG_COMMAND_POLL = "COMMAND_POLL"
MSG_COMMAND      = "COMMAND"
MSG_RESULT       = "RESULT"
MSG_FINISH       = "FINISH"
MSG_METRICS      = "METRICS"
MSG_TERMINATE    = "TERMINATE"