# Connection settings
SERVER_HOSTNAME     = "202.92.129.205"
SERVER_PORT         = 8765
SERVER_PING_TIMEOUT = None

# Session constants
SESSION_CONNECTED    = "CONNECTED"
SESSION_DISCONNECTED = "DISCONNECTED"

# Message constants
MSG_CONNECTION      = "CONNECTION"
MSG_COMMAND         = "COMMAND"
MSG_RESULT          = "RESULT"
MSG_COMMAND         = "COMMAND"

